language: node_js

node_js: "7"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run build:prod

notifications:
  webhooks:
    urls:
      - https://jenkins.darlin.me/job/darlin.me/build?token=069d9f19a9cebf4adec7be0bd55c10d6
    on_success: change
