version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: darlin-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm i --registry https://registry.npmjs.org
      - run:
          name: Build
          command: npm run build:prod
      - save_cache:
          key: darlin-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
